### PR TITLE
chore: updating dependabot to support GHA, python, JS, TS, docker and dev container packages

### PR DESCRIPTION
**Pull request by rajpalc7**

### CODE REVIEW

**Comment by rajpalc7** [comment]
Hi @WadeBarnes, this is ready for review now.

**Review by WadeBarnes — APPROVED** [review]
LGTM, but I'll leave the final review and approval to the regular maintainers.

**Comment by jamshale** [comment]
I'm not sure if we want to manage adding another section to the dependabot config everytime. I didn't know it was like this already. Although the changes to weekly are good.

Is it possible just to have a single config for each type at the root directory?

**Comment by WadeBarnes** [comment]
Unfortunately you have to point Dependabot at the folder containing the dependency manifests.  It's not smart enough to search the folders to find the manifests.

**Comment by swcurran** [comment]
Having instructions to update the dependabot config when adding a plugin is not a bad thing. We don't add them that often...

I assume that is the issue?

**Comment by jamshale** [comment]
> Having instructions to update the dependabot config when adding a plugin is not a bad thing. We don't add them that often...
> 
> I assume that is the issue?

Ya. Mostly just managing all the places. Some of the plugins have multiple places/configs nested inside them. For the simpler plugins it's only the root and integration test folder.

We can merge it though and see how it goes. Maybe figure something out in the future.

**Pull request merged**
