### PR TITLE
Feat/21 run integration tests on pr

### PR DESCRIPTION
**Pull request by jamshale**
Will run integration tests for plugins with changes on PR creation or edit.

### CODE REVIEW

**Comment by dbluhm** [comment]
Since this repo will contain many plugins, it doesn't seem ideal for literally all the plugin's integration tests to run for an update to just a single plugin. Additionally, given that integration testing generally spins up containers and services, integration testing can be quite slow; running each set serially will become tedious to wait for.

**Comment by jamshale** [comment]
This has a script command in the github action to determine which plugins have changes and only run those integration tests now.

**Comment by dbluhm** [comment]
@jamshale can we touch a file in one of the plugins just to see the action running?

**Comment by jamshale** [comment]
@dbluhm I added a commit for a small change to multitenant provider plugin and pushed it. You can see the action running only those integration tests now.

**Comment by dbluhm** [comment]
Nice! Looks good!

**Pull request merged**
