### PR TITLE
Bugfix: vc.credentialSubject.id, vc.issuer, iss, and sub should be DID itself

### PR DESCRIPTION
**Pull request by t-kanuma**
[OID4VCI]
credentialSubject.id, iss, and sub should be DID, not DID URLs pointing to verification methods.

### CODE REVIEW

**Comment by dbluhm** [comment]
Could you point me to relevant documentation on this? Thanks!

**Comment by t-kanuma** [comment]
@dbluhm 
um, probably here?

https://www.w3.org/TR/vc-data-model/#identifiers
> The value of the id [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be a single [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri). It is RECOMMENDED that the [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) in the id be one which, **if dereferenced, results in a document containing machine-readable information about the id.**

I'm a beginner in this field, so I'm not quite sure, but I've never seen before that 'credentialSubject.id' and 'issuer' values are DID URLs pointing to Verification Methods, and it feels uncommon to me. Is there any rational reason for this?

**Comment by dbluhm** [comment]
Thanks! And welcome to the field! I think you must be right. I'm trying to think back to why we chose to use DID URLs to verification method IDs at the time. I might have to spend some time looking deeper at this. Unfortunately, that might be a bit before I can look too much closer.

Would you be able to look into the test failures? DCO especially will need to be taken care of. The `Details` link should provide some pretty detailed instructions on how to handle that. Thanks!

**Comment by t-kanuma** [comment]
Thanks.

> Would you be able to look into the test failures?
Yes sure. I'll take care of it soon.

**Pull request closed without merging**
